from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
import time

path = r"C:\Users\C NAVEEN\PycharmProjects\capgemini_sprint2\drivers\chromedriver.exe"
option = Options()
option.add_argument("--disable-infobars")
option.add_argument("start-maximized")
option.add_argument("--disable-extensions")
option.add_experimental_option("prefs", {
    "profile.default_content_setting_values.notifications": 2
})

driver = webdriver.Chrome(options=option, executable_path=path)
driver.maximize_window()
driver.get("https://www.facebook.com/")
driver.maximize_window()
driver.implicitly_wait(20)
time.sleep(3)

driver.find_element("xpath",'//input[@class="inputtext _55r1 _6luy"]').send_keys('7989315252')
driver.find_element("xpath",'//input[@class="inputtext _55r1 _6luy _9npi"]').send_keys('Naveen@12')
driver.find_element("xpath",'//div[@class ="_6ltg"]//button[@name="login"]').click()
driver.find_element("xpath",'(//span[@class="x1lliihq x6ikm8r x10wlt62 x1n2onr6"])[5]').click()
time.sleep(3)
# driver.find_element("xpath",'//div[@aria-label="New Message"]').click()
#
# driver.find_element("xpath",'(//div[@aria-label="Friends"])[1]//span[text()="Friend requests"]').click()
# time.sleep(3)
# # driver.find_element("xpath",'(//div[@aria-label="Confirm"])[3]').click()
# driver.find_element("xpath",'//span[text()="View sent requests"]').click()
# time.sleep(3)
# driver.find_element("xpath",'//span[text()="Cancel Request"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//div[@class="x92rtbv x10l6tqk x1tk7jg1 x1vjfegm"]').click()
# time.sleep(3)
# driver.find_element("xpath",'(//a[@href="/friends/"])[1]').click()
# time.sleep(3)
# driver.find_element("xpath",'//span[text()="Suggestions"]').click()
# time.sleep(3)
# driver.find_element("xpath",'(//span[text()="Add Friend"])[1]').click()
# time.sleep(6)
# driver.find_element("xpath",'(//span[text()="Remove"])[2]').click()
# time.sleep(3)
# driver.find_element("xpath",'(//a[@href="/friends/"])[1]').click()
# time.sleep(3)
# driver.find_element("xpath",'//span[text()="All Friends"]').click()
# time.sleep(3)
#
# driver.find_element("xpath",'//input[@class="x1i10hfl xggy1nq x1s07b3s x1kdt53j x1yc453h xhb22t3 xb5gni xcj1dhv x2s2ed0 xq33zhf xjyslct xjbqb8w x6umtig x1b1mbwd xaqea5y xav7gou xnwf7zb x40j3uw x1s7lred x15gyhx8 x9f619 xzsf02u xdl72j9 x1iyjqo2 xs83m0k xjb2p0i x6prxxf xeuugli x1a2a7pz x1n2onr6 x15h3p50 xm7lytj xsyo7zv xdvlbce x16hj40l xc9qbxq"]').click()
# time.sleep(3)
# driver.find_element("xpath", '(//div[@aria-label="More"])[3]').click()
# time.sleep(3)
# driver.find_element("xpath", '(//div[@role="menuitem"])[1]').click()
# time.sleep(3)
# driver.find_element("css selector",'g[stroke-linecap="round"]').click()
# time.sleep(2)
# driver.find_element("xpath", '(//div[@aria-label="More"])[3]').click()
# time.sleep(3)
# driver.find_element("xpath", '(//div[@role="menuitem"])[3]').click()
# time.sleep(3)
# driver.find_element("xpath",'//div[@aria-label="Cancel"]').click()
# driver.find_element("xpath", '(//div[@aria-label="More"])[3]').click()
# time.sleep(3)
# driver.find_element("xpath", '(//div[@role="menuitem"])[4]').click()
# time.sleep(3)
# driver.find_element("xpath",'//span[text()="Cancel"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//a[@aria-label="Friends"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//span[text()="Birthdays"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//a[@aria-label="Friends"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//span[text()="Custom lists"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//span[text()="Close friends"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//a[@aria-label="Friends"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//div[@class="x1i10hfl x6umtig x1b1mbwd xaqea5y xav7gou x1ypdohk xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r x16tdsg8 x1hl2dhg xggy1nq x87ps6o x1lku1pv x1a2a7pz x6s0dn4 x14yjl9h xudhj91 x18nykt9 xww2gxu x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x78zum5 xl56j7k xexx8yu x4uap5 x18d9i69 xkhd6sd x1n2onr6 xc9qbxq x14qfxbe x1qhmfi1"]').click()
# time.sleep(3)
# driver.find_element("xpath", '//input[@class="x1i10hfl x9f619 xggy1nq x1s07b3s x1ypdohk x5yr21d xdj266r x11i5rnm xat24cr x1mh8g0r x1w3u9th x1a2a7pz xexx8yu x4uap5 x18d9i69 xkhd6sd x10l6tqk x17qophe x13vifvy xh8yej3"]').click()
# time.sleep(3)
# driver.close()